# Zabbix with Let's Encrypt in a Docker Compose

# Author
# hey, I’m Vladimir Mikhalev, but my friends call me Valdemar.

# My website with detailed IT guides: https://www.heyvaldemar.com/
# Follow me on YouTube: https://www.youtube.com/channel/UCf85kQ0u1sYTTTyKVpxrlyQ?sub_confirmation=1
# Follow me on Twitter: https://twitter.com/heyValdemar
# Follow me on Instagram: https://www.instagram.com/heyvaldemar/
# Follow me on Facebook: https://www.facebook.com/heyValdemarFB/
# Follow me on TikTok: https://www.tiktok.com/@heyvaldemar
# Follow me on [LinkedIn](https://www.linkedin.com/in/heyvaldemar/)
# Follow me on [GitHub](https://github.com/heyvaldemar)

# GitHub https://github.com/heyValdemar/zabbix-traefik-letsencrypt-docker-compose/blob/main/zabbix-traefik-letsencrypt-docker-compose.yml
# Site https://www.heyvaldemar.net/ustanovka-zabbix-s-docker-compose/

# Communication
# Chat with IT pros on Discord: https://discord.gg/AJQGCCBcqf
# Reach me at ask@sre.gg

# Give Thanks
# Support on GitHub: https://github.com/sponsors/heyValdemar
# Support on Patreon: https://www.patreon.com/heyValdemar
# Support on BuyMeaCoffee: https://www.buymeacoffee.com/heyValdemar
# Support on Ko-fi: https://ko-fi.com/heyValdemar
# Support on PayPal: https://www.paypal.com/paypalme/heyValdemarCOM

# Install Docker Engine and Docker Compose by following my guide: https://www.heyvaldemar.com/install-docker-engine-and-docker-compose-on-ubuntu-server/

# Run zabbix-restore-database.sh to restore database if needed.

# Deploy Zabbix server with a Docker Compose using the command:
# docker compose -f zabbix-traefik-letsencrypt-docker-compose.yml -p zabbix up -d

# Detailed installation guide can be found on my website: https://www.heyvaldemar.com/install-zabbix-with-docker-compose/

volumes:
  zabbix-postgres:
  zabbix-postgres-backups:
  traefik-certificates:

services:
  postgres:
    # Image tag (replace with yours)
    image: postgres:14
    volumes:
      - zabbix-postgres:/var/lib/postgresql/data
    environment:
      # Database name (replace with yours)
      POSTGRES_DB: zabbixdb
      # Database user (replace with yours)
      POSTGRES_USER: zabbixdbuser
      # Database password (replace with yours)
      POSTGRES_PASSWORD: FmuHw92hiFZfJNzKvzgNwsf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h 127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  zabbix:
    # Image tag (replace with yours)
    image: zabbix/zabbix-server-pgsql:6.2.0-ubuntu
    environment:
      DB_SERVER_HOST: postgres
      DB_SERVER_PORT: 5432
      # Database name (replace with yours)
      POSTGRES_DB: zabbixdb
      # Database user (replace with yours)
      POSTGRES_USER: zabbixdbuser
      # Database password (replace with yours)
      POSTGRES_PASSWORD: FmuHw92hiFZfJNzKvzgNwsf
      ZBX_VALUECACHESIZE: 64M
      ZBX_CACHESIZE: 128M
      ZBX_TRENDCACHESIZE: 128M
    ports:
      - "10051:10051"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

  web:
    # Image tag (replace with yours)
    image: zabbix/zabbix-web-nginx-pgsql:ubuntu-6.2.0
    environment:
      DB_SERVER_HOST: postgres
      DB_SERVER_PORT: 5432
      # Database name (replace with yours)
      POSTGRES_DB: zabbixdb
      # Database user (replace with yours)
      POSTGRES_USER: zabbixdbuser
      # Database password (replace with yours)
      POSTGRES_PASSWORD: FmuHw92hiFZfJNzKvzgNwsf
      ZBX_SERVER_HOST: zabbix
      ZBX_SERVER_PORT: 10051
      # Timezone (replace with yours) https://www.php.net/manual/en/timezones.php
      PHP_TZ: Europe/Prague
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    labels:
      - "traefik.enable=true"
      # Zabbix URL (replace with yours)
      - "traefik.http.routers.zabbix.rule=Host(`zabbix.heyvaldemar.net`)"
      - "traefik.http.routers.zabbix.service=zabbix"
      - "traefik.http.routers.zabbix.entrypoints=websecure"
      - "traefik.http.services.zabbix.loadbalancer.server.port=8080"
      - "traefik.http.routers.zabbix.tls=true"
      - "traefik.http.routers.zabbix.tls.certresolver=letsencrypt"
      - "traefik.http.services.zabbix.loadbalancer.passhostheader=true"
      - "traefik.http.routers.zabbix.middlewares=compresstraefik"
      - "traefik.http.middlewares.compresstraefik.compress=true"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      traefik:
        condition: service_healthy

  agent:
    # Image tag (replace with yours)
    image: zabbix/zabbix-agent2:6.2.0-ubuntu
    environment:
      # Zabbix Hostname (replace with yours)
      # Set as DNS name on Zabbix server host configuration screen to make checks of Zabbix server itself
      ZBX_HOSTNAME: zabbix.heyvaldemar.net
      ZBX_SERVER_HOST: 0.0.0.0/0
    ports:
      - "10050:10050"
    restart: unless-stopped
    depends_on:
      - postgres
      - zabbix

  traefik:
    # Image tag (replace with yours)
    image: traefik:2.8
    command:
      - "--log.level=WARN"
      - "--accesslog=true"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--ping=true"
      - "--ping.entrypoint=ping"
      - "--entryPoints.ping.address=:8082"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--providers.docker=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.exposedByDefault=false"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      # Email for Let's Encrypt (replace with yours)
      - "--certificatesresolvers.letsencrypt.acme.email=callvaldemar@gmail.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme/acme.json"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.buckets=0.1,0.3,1.2,5.0"
      - "--global.checkNewVersion=true"
      - "--global.sendAnonymousUsage=false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik-certificates:/etc/traefik/acme
    ports:
      - "80:80"
      - "443:443"
    healthcheck:
      test: ["CMD", "wget", "http://localhost:8082/ping","--spider"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    labels:
      - "traefik.enable=true"
      # Traefik URL (replace with yours)
      - "traefik.http.routers.dashboard.rule=Host(`traefik.zabbix.heyvaldemar.net`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.services.dashboard.loadbalancer.server.port=8080"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.services.dashboard.loadbalancer.passhostheader=true"
      - "traefik.http.routers.dashboard.middlewares=authtraefik"
      # Basic Authentication for Traefik Dashboard
      # Username: traefikadmin (replace with yours)
      # Passwords must be encoded using MD5, SHA1, or BCrypt https://hostingcanada.org/htpasswd-generator/
      - "traefik.http.middlewares.authtraefik.basicauth.users=traefikadmin:$$2y$$10$$sMzJfirKC75x/hVpiINeZOiSm.Jkity9cn4KwNkRvO7hSQVFc5FLO"
      - "traefik.http.routers.http-catchall.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    restart: unless-stopped

  backups:
    # Image tag (replace with yours)
    image: postgres:14
    # Database backups prune interval (replace with yours). Default is 7 days.
    # find /srv/zabbix-postgres/backups -type f -mtime +7 | xargs rm -f

    # Zabbix backups interval (replace with yours). Default is 1 day.
    # sleep 24h

    # Run zabbix-restore-database.sh to restore database if needed.
    command: sh -c 'sleep 30m
             && while true; do
             PGPASSWORD="$$(echo $$POSTGRES_PASSWORD)"
             pg_dump
             -h postgres
             -p 5432
             -d zabbixdb
             -U zabbixdbuser | gzip > /srv/zabbix-postgres/backups/zabbix-postgres-backup-$$(date "+%Y-%m-%d_%H-%M").gz
             && find /srv/zabbix-postgres/backups -type f -mtime +7 | xargs rm -f;
             sleep 24h; done'
    volumes:
      # Database backups location
      - zabbix-postgres-backups:/srv/zabbix-postgres/backups
    environment:
      # Database password (replace with yours)
      POSTGRES_PASSWORD: FmuHw92hiFZfJNzKvzgNwsf
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      web:
        condition: service_healthy