version: '1.0'

services:
 postgres-server:
   image: postgres:15.2
   volumes:
    # Базы будут храниться локально на главной системе
    - ./postgres-server/var/lib/postgresql/data:/var/lib/postgresql/data:rw
    # Файлы сертификатов для базы и веб сервиса
    - ./postgres-server/.ZBX_DB_CA_FILE:/run/secrets/root-ca.pem:ro
    - ./postgres-server/.ZBX_DB_CERT_FILE:/run/secrets/server-cert.pem:ro
    - ./postgres-server/.ZBX_DB_KEY_FILE:/run/secrets/server-key.pem:ro
   restart: always
   env_file:
    - ./env/env-pgsql
   secrets:
    - POSTGRES_USER
    - POSTGRES_PASSWORD
   stop_grace_period: 1m
   networks:
    zbx_net_backend:
     aliases:
      - postgres-server
      - pgsql-server
      - pgsql-database

 zabbix-server-1:
  image: zabbix/zabbix-server-pgsql:ubuntu-6.4.0
  ports:
   - "10051:10051"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - ./zabbix_server-1/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
   - ./zabbix_server-1/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
   - ./zabbix_server-1/var/lib/zabbix/dbscripts:/var/lib/zabbix/dbscripts:ro
   - ./zabbix_server-1/var/lib/zabbix/export:/var/lib/zabbix/export:rw
   - ./zabbix_server-1/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
   - ./zabbix_server-1/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
   - ./zabbix_server-1/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
   - ./zabbix_server-1/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
   - snmptraps:/var/lib/zabbix/snmptraps:rw
  restart: always
  ulimits:
   nproc: 65535
   nofile:
    soft: 20000
    hard: 40000
  deploy:
   resources:
    limits:
      cpus: '0.70'
      memory: 1G
    reservations:
      cpus: '0.5'
      memory: 512M
  env_file:
   - ./env/env-pgsql
   - ./env/env-zbx-server-1
  secrets:
   - POSTGRES_USER
   - POSTGRES_PASSWORD
  depends_on:
   - postgres-server
  networks:
   zbx_net_backend:
     aliases:
      - zabbix-server-1
      - zabbix-server-pgsql1
      - zabbix-server-debian-pgsql1
      - zabbix-server-pgsql-debian1
   zbx_net_frontend:
  stop_grace_period: 30s
  sysctls:
   - net.ipv4.ip_local_port_range=1024 65000
   - net.ipv4.conf.all.accept_redirects=0
   - net.ipv4.conf.all.secure_redirects=0
   - net.ipv4.conf.all.send_redirects=0
  labels:
   com.zabbix.description: "Zabbix server with PostgreSQL database support"
   com.zabbix.company: "SiaS LLC"
   com.zabbix.component: "zabbix-server-1"
   com.zabbix.dbtype: "pgsql"
   com.zabbix.os: "debian"

#  zabbix-server-2:
#   image: zabbix/zabbix-server-pgsql:ubuntu-6.4.0
#   ports:
#    - "10061:10061"
#   volumes:
#    - /etc/localtime:/etc/localtime:ro
#    - ./zabbix_server-2/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
#    - ./zabbix_server-2/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
#    - ./zabbix_server-2/var/lib/zabbix/dbscripts:/var/lib/zabbix/dbscripts:ro
#    - ./zabbix_server-2/var/lib/zabbix/export:/var/lib/zabbix/export:rw
#    - ./zabbix_server-2/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
#    - ./zabbix_server-2/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
#    - ./zabbix_server-2/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
#    - ./zabbix_server-2/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
#    - snmptraps:/var/lib/zabbix/snmptraps:rw
#   restart: always
#   ulimits:
#    nproc: 65535
#    nofile:
#     soft: 20000
#     hard: 40000
#   deploy:
#    resources:
#     limits:
#       cpus: '0.70'
#       memory: 1G
#     reservations:
#       cpus: '0.5'
#       memory: 512M
#   env_file:
#    - ./env/env-pgsql
#    - ./env/env-zbx-server-2
#   secrets:
#    - POSTGRES_USER
#    - POSTGRES_PASSWORD
#   depends_on:
#    - postgres-server
#   networks:
#    zbx_net_backend:
#      aliases:
#       - zabbix-server-2
#       - zabbix-server-pgsql2
#       - zabbix-server-debian-pgsql2
#       - zabbix-server-pgsql-debian2
#    zbx_net_frontend:
#   stop_grace_period: 30s
#   sysctls:
#    - net.ipv4.ip_local_port_range=1024 65000
#    - net.ipv4.conf.all.accept_redirects=0
#    - net.ipv4.conf.all.secure_redirects=0
#    - net.ipv4.conf.all.send_redirects=0
#   labels:
#    com.zabbix.description: "Zabbix server with PostgreSQL database support"
#    com.zabbix.company: "SiaS LLC"
#    com.zabbix.component: "zabbix-server-2"
#    com.zabbix.dbtype: "pgsql"
#    com.zabbix.os: "debian"

 zabbix-agent-1:
  image: zabbix/zabbix-agent:ubuntu-6.4.0
  ports:
   - "10050:10050"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - ./zabbix_server-1/etc/zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
   - ./zabbix_server-1/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
   - ./zabbix_server-1/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
   - ./zabbix_server-1/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
  deploy:
   resources:
    limits:
      cpus: '0.2'
      memory: 128M
    reservations:
      cpus: '0.1'
      memory: 64M
   mode: global
  env_file:
   - ./env/env-zbx-agent-1
  privileged: true
  pid: "host"
  networks:
   zbx_net_backend:
    aliases:
     - zabbix-agent-1
     - zabbix-agent-passive1
     - zabbix-agent-debian1
  stop_grace_period: 5s
  labels:
   com.zabbix.description: "Zabbix agent"
   com.zabbix.company: "SiaS LLC"
   com.zabbix.component: "zabbix-agentd"
   com.zabbix.os: "debian"

#  zabbix-agent-2:
#   image: zabbix/zabbix-agent:ubuntu-6.4.0
#   ports:
#    - "10060:10060"
#   volumes:
#    - /etc/localtime:/etc/localtime:ro
#    - ./zabbix_server-2/etc/zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
#    - ./zabbix_server-2/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
#    - ./zabbix_server-2/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
#    - ./zabbix_server-2/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
#   deploy:
#    resources:
#     limits:
#       cpus: '0.2'
#       memory: 128M
#     reservations:
#       cpus: '0.1'
#       memory: 64M
#    mode: global
#   env_file:
#    - ./env/env-zbx-agent-2
#   privileged: true
#   # pid: "host"
#   networks:
#    zbx_net_backend:
#     aliases:
#      - zabbix-agent-2
#      - zabbix-agent-passive2
#      - zabbix-agent-debian2
#   stop_grace_period: 5s
#   labels:
#    com.zabbix.description: "Zabbix agent"
#    com.zabbix.company: "SiaS LLC"
#    com.zabbix.component: "zabbix-agentd"
#    com.zabbix.os: "debian"

 zabbix-web-nginx-pgsql:
  image: zabbix/zabbix-web-nginx-pgsql:ubuntu-6.4.0
  ports:
   - "80:8080"
   - "443:8443"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - ./web/etc/ssl/nginx:/etc/ssl/nginx:ro
   - ./web/usr/share/zabbix/modules/:/usr/share/zabbix/modules/:ro
   #   - ./env_vars/.ZBX_DB_CA_FILE:/run/secrets/root-ca.pem:ro
   #   - ./env_vars/.ZBX_DB_CERT_FILE:/run/secrets/client-cert.pem:ro
   #   - ./env_vars/.ZBX_DB_KEY_FILE:/run/secrets/client-key.pem:ro
  restart: always
  deploy:
   resources:
    limits:
      cpus: '0.70'
      memory: 512M
    reservations:
      cpus: '0.5'
      memory: 256M
  env_file:
   - ./env/env-pgsql
   - ./env/env-web
  secrets:
   - POSTGRES_USER
   - POSTGRES_PASSWORD
  depends_on:
   - postgres-server
  healthcheck:
   test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
   interval: 10s
   timeout: 5s
   retries: 3
   start_period: 30s
  networks:
   zbx_net_backend:
    aliases:
     - zabbix-web
     - zabbix-web-nginx-pgsql
     - zabbix-web-nginx-debian-pgsql
     - zabbix-web-nginx-pgsql-debian
   zbx_net_frontend:
  stop_grace_period: 15s
  sysctls:
   - net.core.somaxconn=65535
  labels:
   com.zabbix.description: "Zabbix frontend on Nginx web-server with PostgreSQL database support"
   com.zabbix.company: "SiaS LLC"
   com.zabbix.component: "zabbix-frontend"
   com.zabbix.webserver: "nginx"
   com.zabbix.dbtype: "pgsql"
   com.zabbix.os: "debian"

 zabbix-java-gateway:
  image: zabbix/zabbix-java-gateway:ubuntu-6.4.0
  ports:
   - "10052:10052"
  restart: always
  deploy:
   resources:
    limits:
      cpus: '0.5'
      memory: 512M
    reservations:
      cpus: '0.25'
      memory: 256M
  env_file:
   - ./env/env-java
  networks:
   zbx_net_backend:
    aliases:
     - zabbix-java-gateway
     - zabbix-java-gateway-debian
  stop_grace_period: 15s
  labels:
   com.zabbix.description: "Zabbix Java Gateway"
   com.zabbix.company: "SiaS LLC"
   com.zabbix.component: "java-gateway"
   com.zabbix.os: "debian"

 zabbix-snmptraps:
  image: zabbix/zabbix-snmptraps:ubuntu-6.4.0
  ports:
   - "162:1162/udp"
  volumes:
   - snmptraps:/var/lib/zabbix/snmptraps:rw
  restart: always
  deploy:
   resources:
    limits:
      cpus: '0.5'
      memory: 256M
    reservations:
      cpus: '0.25'
      memory: 128M
  env_file:
   - ./env/env-pgsql
   - ./env/env-web
  networks:
   zbx_net_backend:
    aliases:
     - zabbix-snmptraps
   zbx_net_frontend:
    aliases:
    - zabbix-snmptraps
  stop_grace_period: 5s
  labels:
   com.zabbix.description: "Zabbix snmptraps"
   com.zabbix.company: "SiaS LLC"
   com.zabbix.component: "snmptraps"
   com.zabbix.os: "debian"

# db_data_pgsql:
#   image: busybox
#   volumes:
#    - ./zbx_env/var/lib/postgresql/data:/var/lib/postgresql/data:rw

volumes:
  snmptraps:

networks:
  zbx_net_frontend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 10.10.2.0/24
  zbx_net_backend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    internal: true
    ipam:
      driver: default
      config:
      - subnet: 10.10.1.0/24

secrets:
  POSTGRES_USER:
    file: ./secrets/POSTGRES_USER
  POSTGRES_PASSWORD:
    file: ./secrets/POSTGRES_PASSWORD